Feature/shop
BCSDLab/JJBAKSA_BACK_END pull request #15
Opened 2022-08-15 16:32 UTC by Yoojkim

### **구현 설명** 
place_id로 상점 검색 후, 외부 api 이용해서 상점 저장 or 현재 DB 상점 정보 반환 

### **세부 설명**
-  ShopService, ShopController, ShopDto, ShopResponse 추가

2022-08-16 05:35 UTC, dpwns523 requested changes

2022-08-16 05:35 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
> +        String placeId=jsonObject_result.get("place_id").toString();
json, objectmapper, dto 키워드로 검색해보시면 dto로 한번에 파싱하는 방식이 있는데 한번 고려해보시는게 좋을 것 같습니다

2022-08-16 05:35 UTC, dpwns523 commented on src/main/resources/db/migration/V3__alter_shop.sql
> +ALTER TABLE shop ADD COLUMN business_day VARCHAR (1000);
기존 테이블을 지우시고 create.sql을 수정하시는게 좋을 것 같습니다

2022-08-17 13:28 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
> +        String placeId=jsonObject_result.get("place_id").toString();
감사합니다! 그 방법도 고려하긴 했는데 계층 구조가 복잡해서 이 방법으로 구현했습니다. 계층 구조가 있는 dto로 구현하는 게 나을지 의견 여쭤봐도 될까요!?

2022-08-17 13:29 UTC, Yoojkim commented on src/main/resources/db/migration/V3__alter_shop.sql
> +ALTER TABLE shop ADD COLUMN business_day VARCHAR (1000);
수정하겠습니다!

2022-08-17 15:22 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
> +        String placeId=jsonObject_result.get("place_id").toString();
필요한 데이터가 계층구조로 복잡하게 되어있으면 objectmapper로 파싱해올 때 dto가 많이 사용되겠지만 거의 고정적으로 데이터를 파싱해온다고 생각하기 때문에 파싱에 필요한 dto패키지를 따로 하나 만들어서 관리를 하면 나중에 유지보수나 코드 이해에도 좋을 것 같다고 생각합니다! 예를 들어 지금 저는 제공되는 json  구조를 모르나 dto를 보면 어디에 어떤 데이터가 묶여있는지 알 수 있으니까요?

2022-08-18 12:15 UTC, Noah981107 commented
수정 하시고 다시 커밋 올려주세요~

2022-08-24 21:26 UTC, tkaltk123 reviewed
추가적으로 저장한 상점 정보를 언제 갱신할지는 논의가 필요할 것 같습니다.

2022-08-24 21:26 UTC, tkaltk123 commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopResponse.java
> +    private ShopCount shopCount;
ShopCount는 Entity라서 ShopCountResponse를 추가하시거나
totalRating, ratingCount를 별도의 필드로 추가하셔야 합니다.

2022-08-24 21:26 UTC, tkaltk123 commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
> +
searchShop은 Page<ShopResponse>를 반환하는게 맞을 것 같습니다.

2022-09-26 06:47 UTC, Noah981107 commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopRequest.java
>      private String keyword;
키워드에 따로 Validation은 없나요?

2022-09-27 14:50 UTC, Noah981107 commented
conflicting 해결 부탁드립니다!

2022-09-30 03:37 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopRequest.java
>      private String keyword;
검색어에 따로 validation을 걸진 않았습니다!
보통 검색어에 validation이 있진 않은 거 같아서요

2022-10-02 08:16 UTC, merged