자동완성 구현
BCSDLab/JJBAKSA_BACK_END pull request #60
Opened 2022-12-16 12:21 UTC by Yoojkim

테스트 코드 추가 예정

2022-12-16 13:08 UTC, Kim-Juwon requested changes
코드 스타일 관련하여 간단히 리뷰 남겨드렸습니다.

2022-12-16 13:08 UTC, Kim-Juwon commented on src/main/java/com/jjbacsa/jjbacsabackend/search/controller/SearchController.java
> +    @GetMapping(value="/autoComplete/{word}")
URI 자원의 네이밍을 camelCase 보다는 하이픈(-)을 이용하는 것이 REST API에서는 더 가독성이 좋다고 합니다.
변경을 고려해도 좋을 듯 합니다.

[참고 링크](https://restfulapi.net/resource-naming/)

2022-12-16 13:08 UTC, Kim-Juwon commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/controller/ShopController.java
> +    @ApiImplicitParam(name="placeId",value="상점 아이디",dataType = "String",dataTypeClass = String.class, paramType = "path")
'=' 사용의 경우에
요소를 전부 붙여서 `a=b` 꼴로 작성하신 경우도 있고 
한칸씩 띄어서 `a = b` 꼴로 작성하신 경우도 있는 것으로 보입니다.

`a=b` 꼴은 코드를 볼때 조금 답답해 보이는 것 같습니다.

별거 아닌 것 같아 보여도 다른 코드와의 통일성을 위해 
`a = b` 꼴로 작성해보는 것이 좋지 않을까 하는 생각입니다!

2022-12-16 16:44 UTC, Choi-JJunho reviewed
전체적으로 코드 포맷팅이 안되어있네요
인텔리제이의 코드 포맷팅 기능으로 작성하신 내용에 대해 전체적으로 포맷팅 한번 부탁드립니다.

단축키
윈도우 : `Ctrl` + `Alt` + `L`
맥 : `Option` + `Cmd` + `L`

2022-12-16 16:44 UTC, Choi-JJunho commented on src/main/java/com/jjbacsa/jjbacsabackend/search/repository/SearchRepository.java
> +    Optional<SearchEntity> getByContent(String Content);
JpaRepository에서 get은 Optional이 아닌 Entity를 바로 가져오는 문장으로 사용되고 있습니다.

Optional을 반환한다면 findBy가 더 어울릴거 같습니다.

2022-12-16 16:44 UTC, Choi-JJunho commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
>          this.objectMapper=objectMapper;
해당 부분에 대해서 `@RequiredArgsConstructor`를 사용하지 않은 이유가 있을까요

2022-12-17 06:22 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/serviceImpl/ShopServiceImpl.java
>          this.objectMapper=objectMapper;
webClient 설정 때문에 생성자 생성하여 진행하였습니다.

2022-12-17 06:22 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/search/repository/SearchRepository.java
> +    Optional<SearchEntity> getByContent(String Content);
네 감사합니다~ 확인해서 수정하도록 하겠습니다.

2022-12-17 06:22 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/controller/ShopController.java
> +    @ApiImplicitParam(name="placeId",value="상점 아이디",dataType = "String",dataTypeClass = String.class, paramType = "path")
확인했습니다 감사합니다~

2022-12-17 06:23 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/search/controller/SearchController.java
> +    @GetMapping(value="/autoComplete/{word}")
이 부분 깜빡하고 고려를 못했네요 ㅠㅠ 수정하는 게 맞는 것 같습니다 수정하겠습니다~

2023-03-13 01:57 UTC, insukL commented on src/main/java/com/jjbacsa/jjbacsabackend/google/response/ShopResponse.java
> +    }
따로 boolean 반환값을 사용하진 않던데, Response에서 Exception을 잡아주는 이유가 있을까요?

2023-03-13 07:44 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/response/ShopResponse.java
> +    }
count table과 상점 정보 저장하는 table이 별개로 있어, 관련하여 혹시 Exception 발생 시에 처리하려고 했던 것 같은데 지금 보니까 불필요한 것 같아서 수정하도록 하겠습니다.

2023-03-13 08:57 UTC, 5junseo commented on src/main/java/com/jjbacsa/jjbacsabackend/google/serviceImpl/GoogleServiceImpl.java
> +        System.out.println(shopStr);
System.out.println() 는 성능저하의 원인이 될 수 있다고 합니다 
[참고 링크](https://www.baeldung.com/java-system-out-println-vs-loggers)
[참고 링크](https://hudi.blog/do-not-use-system-out-println-for-logging/)

2023-03-13 12:30 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleController.java
> +            notes = "키워드와 반경으로 상점들을 검색하여 반환한다.\n\n"
API 설명 수정이 되지 않은 것 같습니다.

2023-03-13 12:30 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/search/entity/SearchEntity.java
> +public class SearchEntity {
엔티티에 빌더패턴을 적용하면 생성자를 여러개 만들지 않아도 되지 않을까요?

2023-03-13 16:09 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/serviceImpl/GoogleServiceImpl.java
> +        System.out.println(shopStr);
확인하고 지운다는 걸 깜빡했네요 감사합니다~

2023-03-13 16:10 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleController.java
> +    @PostMapping("/google/shops/{page_token}")
url이 아니라 pathvarible도 수정해야 하나요?

2023-03-13 16:12 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleController.java
> +            notes = "키워드와 반경으로 상점들을 검색하여 반환한다.\n\n"
앟 넵 감사합니다!

2023-03-13 16:54 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/search/entity/SearchEntity.java
> +public class SearchEntity {
원래는 Entity와 builder, noargsconstructor, allargsconstructor 사이 설정이 꼬여서 저렇게 구현했던 건데 관련하여 해결해서 다시 재구성했습니다 감사합니다~

2023-03-14 00:06 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleController.java
> +    @PostMapping("/google/shops/{page_token}")
문서의 Best Practice 예시를 보면 그렇게 되어 있어서 저도 수정 했습니다!

[참고 링크](https://restfulapi.net/resource-naming/)

2023-03-18 05:59 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
잘못된 요청에 대한 에러 핸들링을 위해 Optional로 받는 것은 어떨까요?

[4.4.7절 참고](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-return-types)

2023-03-18 05:59 UTC, dpwns523 commented on src/main/resources/db/migration/V9__add_google_and_search_table.sql
> +    place_id      VARCHAR(255) NOT NULL
ShopResponse에 id값 없이 place_id만 반환해서 review와 연관관계 매핑 시 place_id를 외래키로 설정하려고 하는데 unique 옵션을 넣는 건 어떤가요?

2023-03-19 06:24 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
Optional 사용할 생각도 있었는데, null이든 아니든 다른 처리를 해줘야해서 저렇게 구현했습니다! 
null 값이 나온다고 해서 어떠한 에러가 발생한 것은 아니라서요.

2023-03-19 06:25 UTC, Yoojkim commented on src/main/resources/db/migration/V9__add_google_and_search_table.sql
> +    place_id      VARCHAR(255) NOT NULL
넵! 수정했습니다~

2023-03-19 07:54 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/response/ShopResponse.java
피그마에 보면 상점 카테고리 정보가 있던데 type도 반환받아야 하는 건지 확인해 주실 수 있나요??

2023-03-19 08:11 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
제 생각은 placeId가 잘못 요청될 일은 거의 없겠지만 프런트든 백엔드든 placeId를 결국 파싱 해서 사용할 텐데 이에 대한 잘못된 파싱 후 요청에 대해 추적할 방법이 없어서 에러 핸들링이 필요하지 않을까 생각했던 거예요

다시 확인해 봤는데, 상점 조회로는 placeId를 DB에 저장하지 않고 리뷰 작성 시에 저장하자고 해서 그러신 것 같습니다. 혹시 placeId만 저장할 거면 상점 첫 조회 시 placeId를 저장하는 건 어떠신가요??

리뷰 측에서 관리하는 건 더 복잡해지는 것 같습니다..

추가로 Optional을 사용하게 되면 orElse로 save 하는 코드 한 줄이면 가능하다고 생각합니다!

2023-03-19 08:38 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/response/ShopResponse.java
넵 그거 관련해서 의견 남길 예정입니다!
회의록에 남겨놨습니당

2023-03-26 07:12 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
상점 조회시 placeId를 저장하게 되면 만약 상점 검색 시에 나오는 상점 20개, 40개에 대해 의미없이 저장하게 돼서요
상점 저장하면 상점 count도 같이 생성되게 되어서 리뷰 작성 시에 저장하는 게 맞다고 생각하는데 이견 있으신가요?

2023-03-26 07:49 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
검색 말고 placeId로 상점 조회 시에만 저장하면 되지 않을까요?

2023-04-02 07:02 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
placeId로 상점 조회 시에도 사용 안할 수도 있어서요. 사용 하지도 않는 데이터를 굳이 가지고 있을 필요는 없다고 생각합니다~

2023-04-02 08:19 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
넵 그러면 그대로 리뷰생성 시 상점정보를 등록하는 식으로 하는게 낫겠네요, 그래도 Optional 로직으로 수정부탁드려요! 결국 리뷰에서 Optional로 받아야해서 같이 수정되어야 합니다 ㅜ

2023-04-02 10:48 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/repository/GoogleShopRepository.java
> +    GoogleShopEntity findByPlaceId(String placeId);
넵 알겠습니다!

2023-05-22 05:03 UTC, Backend-Changyeon requested changes
API 디자인 관련된 부분이 있어서 그부분들은 수정 이후 머지되면 좋을 것 같습니다!

2023-05-22 05:03 UTC, Backend-Changyeon commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopDto.java
> +                shopApiDto.getTypes().isEmpty() || shopApiDto.getPlace_id() == null ||
이부분은 조건이 꽤 길어서 Dto 단에서 validation 체크가 되어서 넘어오면 좋을 것 같은데 고민만 부탁드립니다!
수정까지는 안되어도 괜찮을것 같아요

2023-05-22 05:36 UTC, dpwns523 commented on src/main/java/com/jjbacsa/jjbacsabackend/google/serviceImpl/GoogleShopServiceImpl.java
> +        log.info("Dist(m): " + String.valueOf(dist));
필요하지 않은 로깅이라면 지우는 편이 좋을 것 같습니다.

2023-05-23 10:39 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/etc/enums/ErrorMessage.java
> +    ZERO_RESULTS_EXCEPTION(16,"구글 API 검색 결과가 없습니다.",HttpStatus.FORBIDDEN),
zero results exception 자체가 google api에서 반환되는 에러 중 있는 부분인데 특정 place_id로 상점 요청했을 때나 쿼리로 여러 상점 검색할 때나 결과가 없으면 해당 에러를 반환하게 되어있습니다! place_id로 상점 요청 시에, 상점 결과가 오지 않을 경우는 Exception 처리를 해야 하는 것이 맞으니 말씀하신 거 반영해서 Exception 처리를 하고 검색어 쿼리로 여러 상점을 검색할 때는 빈 값을 반환하는 부분으로 수정하도록 하겠습니다~

2023-05-23 10:45 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleShopController.java
> +    @PostMapping("/google/shops/page/{page_token}")
이 부분은 사용자와의 거리 계산 때문에 사용자 위치 좌표가 필요해서 해당 좌표를 body를 통해 request dto로 받아오려고 했습니다! 좌표가 url에 나타나면 좀 그래서요..!

2023-05-23 11:34 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopDto.java
> +                shopApiDto.getTypes().isEmpty() || shopApiDto.getPlace_id() == null ||
이 부분은 현재 사용하는 코드는 아니라서요..!! 로직 수정되기 이전 코드인데 로직 변경될 수도 있다고 하셔서 남겨놓은 거라 일단 수정 없이 남겨놓고 추후에 사용되면 그때 변경하도록 하겠습니다!

2023-05-23 23:38 UTC, Backend-Changyeon commented on src/main/java/com/jjbacsa/jjbacsabackend/shop/dto/ShopDto.java
> +                shopApiDto.getTypes().isEmpty() || shopApiDto.getPlace_id() == null ||
@Yoojkim 좋습니다!

2023-05-24 00:59 UTC, Yoojkim commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleShopController.java
> +    @PostMapping("/google/shops/{keyword}")
@Backend-Changyeon Query parameter 말씀하시는 거죠!? 해당 부분이라면 그렇게 수정하는 부분이 맞는 것 같아 수정하겠습니다!

2023-05-24 01:03 UTC, Backend-Changyeon commented on src/main/java/com/jjbacsa/jjbacsabackend/google/controller/GoogleShopController.java
> +    @PostMapping("/google/shops/{keyword}")
@Yoojkim 좋습니다!

2023-05-24 13:33 UTC, merged